### ISSUE TITLE
Not working with Grav's Admin Panel

### ISSUE THREAD

**Issue by jpfleury** [bobrocke/grav-plugin-materializer#1]
The plugin Materializer can't be configured using the new [Grav's Admin Panel](https://github.com/getgrav/grav-plugin-admin). For example, if we go to the settings page of the plugin (url `/admin/plugins/materializer`) and click on *Save*, there's the following error:

> **Validation failed:** always_load is not defined in blueprints

According to a Grav developer: "These plugins just need to get updated with appropriate blueprint files so they will work in the admin plugin."

My config: Grav v0.9.39, Admin Panel v0.4.2, Materializer v1.3.0

**Comment by bobrocke** [comment]
I haven't updated For the Admin yet as I'm not 100% sure of the blueprint format yet (it hasn't been documented with the Admin still in beta). I'll take a look at it this weekend and see what can be done.

Thanks for the heads up and the interest in Materializer.

**Comment by jpfleury** [comment]
Thanks for this quick answer.

**Comment by jpfleury** [comment]
I asked a Grav developer about blueprint format. Answer:

> We are in the process of documenting these. Hopefully next week we will have some preliminary blueprint documents.
> 
> In the meantime, you can see examples in the various blueprints in `system/blueprints` however. This will give you an idea about the possible blueprint values.

**Comment by bobrocke** [comment]
Thanks. Of course you can still configure the plug-in just fine by editing the YAML files, as always. :)

**Comment by bobrocke** [comment]
Fixed in v1.3.1.

**Comment by jpfleury** [comment]
Thanks a lot.
