### ISSUE TITLE
Does this plugin deactivate other css/js automatically?

### ISSUE THREAD

**Issue by Sajonara** [bobrocke/grav-plugin-materializer#2]
I came here to ask if I have to deactivate existing template's CSS and JS or if it is done automatically by activating this plugin? Because every template uses its own CSS and JS, I don't want both of them being loaded for page loading reasons, but deactivate the existing. Is this done automatically? Or do I have to edit the templates of the themes to do so? That would be no problem, but as I am new to Grav I'd better ask. I use materialize a lot in my Rails projects hence I wanted to try it on a microsite with Grav. I just recently installed it.

**Comment by bobrocke** [comment]
Materializer should be deactivating CSS and JS from other themes. Other plug-ins, however, may still use their own.

Do you have a specific example I could look into?
